"""empty message

Revision ID: 4bfaf09d12c4
Revises: e14611d57860
Create Date: 2023-05-29 18:23:18.278131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bfaf09d12c4'
down_revision = 'e14611d57860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('ImagePath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImagePath', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
