"""empty message

Revision ID: 5cf5887f12b8
Revises: ffc7cc1affbc
Create Date: 2023-06-04 18:58:07.673821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf5887f12b8'
down_revision = 'ffc7cc1affbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('TagID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TagID')
    )
    op.create_table('product_tag',
    sa.Column('ProductTagID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('TagID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ProductID'], ),
    sa.ForeignKeyConstraint(['TagID'], ['tag.TagID'], ),
    sa.PrimaryKeyConstraint('ProductTagID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
