"""Initial migration.

Revision ID: a68efc2385d5
Revises: 
Create Date: 2023-05-07 17:36:35.799359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68efc2385d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('AddressID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('StreetName', sa.String(length=50), nullable=True),
    sa.Column('StreetNo', sa.String(length=10), nullable=True),
    sa.Column('AppartmentNo', sa.String(length=10), nullable=True),
    sa.Column('PostCode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('AddressID')
    )
    op.create_table('product_type',
    sa.Column('ProductTypeID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ProductTypeID')
    )
    op.create_table('set',
    sa.Column('SetID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('SetNo', sa.String(length=50), nullable=False),
    sa.Column('Price', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=250), nullable=False),
    sa.Column('ImagePath', sa.String(length=255), nullable=False),
    sa.Column('Availability', sa.Integer(), nullable=False),
    sa.Column('UnitsSold', sa.Integer(), nullable=False),
    sa.Column('ReleaseDate', sa.Date(), nullable=False),
    sa.Column('PieceCount', sa.Integer(), nullable=False),
    sa.Column('Instruction', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('SetID')
    )
    op.create_table('shopping_cart',
    sa.Column('ShoppingCartID', sa.Integer(), nullable=False),
    sa.Column('ShippingCost', sa.Integer(), nullable=False),
    sa.Column('NumberOfItems', sa.Integer(), nullable=False),
    sa.Column('TotalPrice', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ShoppingCartID')
    )
    op.create_table('user',
    sa.Column('Userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('ShoppingCartID', sa.Integer(), nullable=True),
    sa.Column('Address', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Userid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('buyinghistory',
    sa.Column('BuyingHistoryID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ShoppingCartID', sa.Integer(), nullable=True),
    sa.Column('DateOfPurchase', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ShoppingCartID'], ['shopping_cart.ShoppingCartID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.Userid'], ),
    sa.PrimaryKeyConstraint('BuyingHistoryID')
    )
    op.create_table('product',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('SetNo', sa.String(length=50), nullable=False),
    sa.Column('Price', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=250), nullable=False),
    sa.Column('ImagePath', sa.String(length=255), nullable=True),
    sa.Column('Availability', sa.Integer(), nullable=False),
    sa.Column('ReleaseDate', sa.Date(), nullable=False),
    sa.Column('PieceCount', sa.Integer(), nullable=False),
    sa.Column('ProductTypeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProductTypeID'], ['product_type.ProductTypeID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('set_product',
    sa.Column('SetProductID', sa.Integer(), nullable=False),
    sa.Column('SetID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ProductID'], ),
    sa.ForeignKeyConstraint(['SetID'], ['set.SetID'], ),
    sa.PrimaryKeyConstraint('SetProductID')
    )
    op.create_table('shoppingcart_product',
    sa.Column('ShoppingCartProductID', sa.Integer(), nullable=False),
    sa.Column('ShoppingCartID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('SetID', sa.Integer(), nullable=True),
    sa.CheckConstraint('ProductID IS NOT NULL OR SetID IS NOT NULL'),
    sa.ForeignKeyConstraint(['ProductID'], ['product.ProductID'], ),
    sa.ForeignKeyConstraint(['SetID'], ['set.SetID'], ),
    sa.ForeignKeyConstraint(['ShoppingCartID'], ['shopping_cart.ShoppingCartID'], ),
    sa.PrimaryKeyConstraint('ShoppingCartProductID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcart_product')
    op.drop_table('set_product')
    op.drop_table('product')
    op.drop_table('buyinghistory')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('shopping_cart')
    op.drop_table('set')
    op.drop_table('product_type')
    op.drop_table('address')
    # ### end Alembic commands ###
