"""Add_ShoppingCartItem

Revision ID: ad2958de19a0
Revises: a68efc2385d5
Create Date: 2023-05-31 22:43:18.899828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2958de19a0'
down_revision = 'a68efc2385d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart_item',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ShoppingCartId', sa.Integer(), nullable=True),
    sa.Column('ProductId', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProductId'], ['product.ProductID'], ),
    sa.ForeignKeyConstraint(['ShoppingCartId'], ['shopping_cart.ShoppingCartID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart_item')
    # ### end Alembic commands ###
